config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'board/posts#index'

  mount Board::Engine, at: '/board'

  get '/account', to: 'users#edit'
  patch '/account', to: 'users#update'
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates_presence_of :body
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :messages
  has_many :post_messages

  validates_presence_of :title

  accepts_nested_attributes_for :messages, reject_if: :all_blank

  def self.new_with_message
    post = new
    post.messages.build
    post
  end
end

app/models/post_listing.rb
class PostListing < ActiveRecord::Base
  self.primary_key = :id

  belongs_to :user
  has_many :messages, class_name: 'PostMessage', foreign_key: :post_id

  private

  def readonly?
    true
  end
end

app/models/post_message.rb
class PostMessage < ActiveRecord::Base
  self.primary_key = :id

  belongs_to :post
  belongs_to :user

  private

  def readonly?
    true
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :messages
  has_many :post_messages

  def full_name
    [first_name, last_name].compact.join(' ')
  end

  def display_name
    full_name.present? ? full_name : email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def edit
    @user = current_user
  end

  def update
    if current_user.update_attributes(user_params)
      redirect_to '/'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessageBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render "static/navbar" %>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/pages/home.html.erb
<h2>Message Board</h2>

<p class="lead">
  Welcome to the message board! Join in on an existing post below or <%= link_to "Start your own discussion", board.new_post_path %>.
</p>

<% @posts.each do |post| %>
  <div class="thread">
    <h3 class="post-title"><%= link_to post.title, board.post_path(post) %></h3>

    <div class="recent-messages">
      <% post.messages.each do |message| %>
        <div class="row message">
          <div class="col-md-3">
            <span class="author"><%= message.user.display_name %></span>
            <span class="message-time">posted <%= time_ago_in_words message.created_at %> ago</span>
          </div>
          <div class="col-md-9">
            <%= simple_format message.body %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= form_for @user, url: account_path, html: { class: 'col-md-4 col-md-offset-4' } do |f| %>
  <h2>Account</h2>

  <div class="well">
    <div class="form-group">
      <%= f.label :first_name %>
      <%= f.email_field :first_name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :last_name %>
      <%= f.email_field :last_name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>

    <div class="form-group text-right">
      <%= link_to "Cancel", :back, class: 'btn btn-link' %>
      <%= f.submit "Save Changes", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>